Numpy

In [1]:
import numpy as np

In [2]:
#2d arra

a = np.array([[1,2,3,4,5],[5,4,3,2,1]])

<LI> One D array = vector
<li> Two D array = Matric
<li> Three D array = Tensor

In [3]:
#dtype
c = np.array([1,2,3,4,5], dtype=bool)
c

array([ True,  True,  True,  True,  True])

In [4]:
c = np.array([1,2,3,4,5], dtype=float)
c

array([1., 2., 3., 4., 5.])

In [5]:
#np.arrange
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [6]:
#np reshape : reshape an array into prefered array shape

np.arange(1,11,1).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
#ones and zeroes: creates an numpy array that are either 0 or 1

np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
#random array create a random 5x5 matrix

np.random.random((5,5))

array([[0.89933441, 0.87239305, 0.05402071, 0.79201149, 0.44465451],
       [0.26011753, 0.50843823, 0.36898384, 0.01797621, 0.34069508],
       [0.0780746 , 0.14042079, 0.25543146, 0.70522784, 0.02270007],
       [0.30190626, 0.02943533, 0.48321095, 0.2900881 , 0.78486283],
       [0.30037137, 0.51747961, 0.19487659, 0.47022049, 0.46957799]])

In [10]:
#np.linspace(lowerRange,UpperRange,HowManyValues): Will generate equal distance between two points

np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [11]:
#np identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#ndim = numbers of dimensions of an array   
a1 = np.arange(10)
a1.ndim

1

In [13]:
# shape = Will tell us the shape of an array
b1 = np.array([[2,2,3],[5,4,6]], dtype=float)
b1.shape

(2, 3)

In [14]:
#size = numbers of items 
b1.size

6

In [15]:
#itemsize = tells us the size of 

b1.itemsize

8

In [16]:
#dtype = tells us the data type 
b1.dtype

dtype('float64')

Changing data type

In [17]:
# astype = change data type
a3 = np.array(([1,2,3],[3,2,1],[3,1,2]))

In [18]:
a3.shape

(3, 3)

In [19]:
a3.astype(np.int32) #This will reduce the size of the file. We use this to optomize code


array([[1, 2, 3],
       [3, 2, 1],
       [3, 1, 2]], dtype=int32)

Operators

In [20]:
a3 = a3 * 5  #scaler multiplication

In [26]:
a3

array([[ 5, 10, 15],
       [15, 10,  5],
       [15,  5, 10]])

In [21]:
#relational 

a3 > 5

array([[False,  True,  True],
       [ True,  True, False],
       [ True, False,  True]])

In [23]:
#max
np.max(a1)

9

In [29]:
#Min in every row
#axis = 0 col and axis = 1 is row
np.max(a3, axis=0)

array([15, 10, 15])

In [32]:
#Stat releated function

# mean
np.mean(a3)

#median
np.median(a3, axis=0)

array([15., 10., 10.])

In [35]:
#Dot product = Multiple of two matrix together 


In [42]:
#round = round the value
#ceil = round it to the next integer 
#floor = crunch it 

np.round((np.random.random((3,3))*100))

array([[58., 76., 11.],
       [35., 78., 80.],
       [81., 49., 42.]])

In [ ]:
#indexing 