Numpy

In [1]:
import numpy as np

In [3]:
#2d arra

a = np.array([[1,2,3,4,5],[5,4,3,2,1]])

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

<LI> One D array = vector
<li> Two D array = Matric
<li> Three D array = Tensor

In [8]:
#dtype
c = np.array([1,2,3,4,5], dtype=bool)
c

array([ True,  True,  True,  True,  True])

In [7]:
c = np.array([1,2,3,4,5], dtype=float)
c

array([1., 2., 3., 4., 5.])