Numpy

In [48]:
import numpy as np

In [49]:
#2d arra

a = np.array([[1,2,3,4,5],[5,4,3,2,1]])

<LI> One D array = vector
<li> Two D array = Matric
<li> Three D array = Tensor

In [50]:
#dtype
c = np.array([1,2,3,4,5], dtype=bool)
c

array([ True,  True,  True,  True,  True])

In [51]:
c = np.array([1,2,3,4,5], dtype=float)
c

array([1., 2., 3., 4., 5.])

In [52]:
#np.arrange
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [53]:
#np reshape : reshape an array into prefered array shape

np.arange(1,11,1).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [54]:
#ones and zeroes: creates an numpy array that are either 0 or 1

np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
#random array create a random 5x5 matrix

np.random.random((5,5))

array([[0.01742633, 0.49597886, 0.92836124, 0.98078674, 0.36881288],
       [0.02202614, 0.86351684, 0.55185646, 0.72800224, 0.77442393],
       [0.01404605, 0.3893253 , 0.790855  , 0.20812457, 0.89192868],
       [0.56882728, 0.25310906, 0.54537524, 0.61425315, 0.20629932],
       [0.86758358, 0.41785357, 0.36588968, 0.9318438 , 0.17178011]])

In [57]:
#np.linspace(lowerRange,UpperRange,HowManyValues): Will generate equal distance between two points

np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [58]:
#np identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
#ndim = numbers of dimensions of an array   
a1 = np.arange(10)
a1.ndim

1

In [60]:
# shape = Will tell us the shape of an array
b1 = np.array([[2,2,3],[5,4,6]], dtype=float)
b1.shape

(2, 3)

In [61]:
#size = numbers of items 
b1.size

6

In [62]:
#itemsize = tells us the size of 

b1.itemsize

8

In [63]:
#dtype = tells us the data type 
b1.dtype

dtype('float64')

Changing data type

In [64]:
# astype = change data type
a3 = np.array(([1,2,3],[3,2,1],[3,1,2]))

In [65]:
a3.shape

(3, 3)

In [66]:
a3.astype(np.int32) #This will reduce the size of the file. We use this to optomize code


array([[1, 2, 3],
       [3, 2, 1],
       [3, 1, 2]], dtype=int32)

Operators

In [67]:
a3 = a3 * 5  #scaler multiplication

In [68]:
a3

array([[ 5, 10, 15],
       [15, 10,  5],
       [15,  5, 10]])

In [69]:
#relational 

a3 > 5

array([[False,  True,  True],
       [ True,  True, False],
       [ True, False,  True]])

In [70]:
#max
np.max(a1)

9

In [71]:
#Min in every row
#axis = 0 col and axis = 1 is row
np.max(a3, axis=0)

array([15, 10, 15])

In [72]:
#Stat releated function

# mean
np.mean(a3)

#median
np.median(a3, axis=0)

array([15., 10., 10.])

In [73]:
#Dot product = Multiple of two matrix together 


In [74]:
#round = round the value
#ceil = round it to the next integer 
#floor = crunch it 

np.round((np.random.random((3,3))*100))

array([[31., 28., 78.],
       [91.,  5., 10.],
       [21., 78., 63.]])

In [75]:
#indexing 
a3[-1]

array([15,  5, 10])

In [76]:
a3

array([[ 5, 10, 15],
       [15, 10,  5],
       [15,  5, 10]])

In [77]:
#specific item in 2d array
a3[1,1]

10

In [78]:
a3 = np.array([[[1,2,3],[3,2,1]],[[4,5,6],[7,5,9]]])
a3

array([[[1, 2, 3],
        [3, 2, 1]],

       [[4, 5, 6],
        [7, 5, 9]]])

In [79]:
#3d array indexing
a3[1,1,0]

7

Slicing

In [86]:
a1 = np.array([1,2,3,4,5,6,7,8,9])
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a1[2:7]

array([3, 4, 5, 6, 7])

In [93]:
a4 = np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
a4[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
#Iteration = running loop over numpy array
for i in a4:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [101]:
for i in np.nditer(a3): #will convert 2d or 3d array into one array
    print(i)

1
2
3
3
2
1
4
5
6
7
5
9


Reshape

In [102]:
#transpose = converts row to column vice-versa
a4


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
np.transpose(a4)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [105]:
#ravel = will also convert 2d ++ array into 1D
a4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking    


In [107]:
#stacking = joining arrays vertically or horizantally 
a5 = np.arange(12).reshape(3,4)
a6 = np.arange(12).reshape(3,4)

In [108]:
np.hstack((a5,a6))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [111]:
x = np.vstack((a5,a6))

Splitting   



In [115]:
#splitting = opposite of stacking either via horizantlly or vertically 

np.hsplit(x,2)

[array([[0, 1],
        [4, 5],
        [8, 9],
        [0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [ 2,  3],
        [ 6,  7],
        [10, 11]])]