Numpy

In [1]:
import numpy as np

In [3]:
#2d arra

a = np.array([[1,2,3,4,5],[5,4,3,2,1]])

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

<LI> One D array = vector
<li> Two D array = Matric
<li> Three D array = Tensor

In [8]:
#dtype
c = np.array([1,2,3,4,5], dtype=bool)
c

array([ True,  True,  True,  True,  True])

In [7]:
c = np.array([1,2,3,4,5], dtype=float)
c

array([1., 2., 3., 4., 5.])

In [9]:
#np.arrange
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [15]:
#np reshape : reshape an array into prefered array shape

np.arange(1,11,1).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
#ones and zeroes: creates an numpy array that are either 0 or 1

np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
#random array create a random 5x5 matrix

np.random.random((5,5))

array([[0.59310181, 0.82187313, 0.63106547, 0.38825477, 0.07988222],
       [0.90527662, 0.32224061, 0.92136455, 0.43212447, 0.6261754 ],
       [0.63173348, 0.00425667, 0.38376913, 0.2525095 , 0.7509071 ],
       [0.49725112, 0.95856304, 0.06368203, 0.745888  , 0.21079124],
       [0.82177696, 0.2793664 , 0.69373565, 0.01542932, 0.80320001]])

In [31]:
#np.linspace(lowerRange,UpperRange,HowManyValues): Will generate equal distance between two points

np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [32]:
#np identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#ndim = numbers of dimensions of an array   
a1 = np.arange(10)
a1.ndim

1

In [41]:
# shape = Will tell us the shape of an array
b1 = np.array([[2,2,3],[5,4,6]], dtype=float)
b1.shape

(2, 3)

In [42]:
#size = numbers of items 
b1.size

6

In [43]:
#itemsize = tells us the size of 

b1.itemsize

8

In [44]:
#dtype = tells us the data type 
b1.dtype

dtype('float64')

Changing data type

In [45]:
# astype = change data type
a3 = np.array(([1,2,3],[3,2,1],[3,1,2]))

In [46]:
a3.shape

(3, 3)

In [49]:
a3.astype(np.int32) #This will reduce the size of the file. We use this to optomize code


array([[1, 2, 3],
       [3, 2, 1],
       [3, 1, 2]], dtype=int32)

Operators

In [55]:
a3 = a3 * 5  #scaler multiplication

In [57]:
#relational 

a3 > 5

array([[False,  True,  True],
       [ True,  True, False],
       [ True, False,  True]])